"""auto-vote

Revision ID: f8bd68b34d9e
Revises: 2c7456bd0202
Create Date: 2024-05-16 19:53:49.705609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8bd68b34d9e'
down_revision: Union[str, None] = '2c7456bd0202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('name', sa.String(), nullable=True))
    op.alter_column('posts', 'user_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               nullable=True)
    op.drop_constraint('post_user_fk', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('posts', 'rehsr')
    op.drop_column('posts', 'title')
    op.add_column('user', sa.Column('password', sa.String(), nullable=True))
    
    op.drop_column('user', 'name')
    op.create_foreign_key(None, 'votes', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'votes', 'posts', ['post_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.add_column('user', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('user', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('user', 'password')
    op.add_column('posts', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('rehsr', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('post_user_fk', 'posts', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('posts', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.drop_column('posts', 'name')
    # ### end Alembic commands ###
