install:
	python3 -m venv myvenv
	pip install --upgrade pip && pip install -r requirements.txt
format:
	#format code
lint:
	#flake8 or #pylint
test:
	#test
deploy:
	#deploy
all: install lint test deploy

